## Copyright © 2021, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl
## Database Development Tools - btspendo

title: "ORDS and Modern Application Development"
stackDescription: "ORDS and Modern Application Development"
schemaVersion: 1.0.0
version: "20220308"
locale: "en"

variableGroups:
- title: General Configuration
  visible: false
  variables:
  - tenancy_ocid
  - release
  - region

- title: Required Configuration
  visible: true  
  variables:
  - compartment_ocid

variables:
  
  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    visible: true
    title: Compartment
    description: "Compartment where you want to create the solution resources"

  region:
    type: oci:identity:region:name
    required: true
    visible: false


outputGroups:
  - title: ${Messages.solutionsHub.solutions.ordsModernAppDev.outputGroups.appDetailsOutputTitle()}
    outputs:
      - autonomous_database_password
      - generated_private_key_pem
      - sdw_url
      - rest_get_url
      - dev
      - adb_password

outputs:

  # heading under Application Information tab
  title: "ORDS and Modern Application Development"
  # text under heading
  description: "ORDS and Modern Application Development"
  # text in blue information box
  informationalText: "ORDS and Modern Application Development"

  rest_get_url:
    title: "Employee GET REST URL"
    displayText: "Employee GET REST URL"
    type: string
    visible: true

  sdw_url:
    title: "SQL Developer Web URL"
    displayText: "SQL Developer Web URL"
    type: string
    visible: true

  adb_password:
    title: "ADB Password"
    displayText: "ADB Password"
    type: string
    visible: true
    
  dev:
    type: string
    title: ${Messages.solutionsHub.solutions.ordsModernAppDev.outputs.devTitle()}
    visible: true

  generated_private_key_pem:
    type: string
    title: ${Messages.solutionsHub.solutions.ordsModernAppDev.outputs.generatedPrivateKeyPemTitle()}
    displayText: ${Messages.solutionsHub.solutions.ordsModernAppDev.outputs.generatedPrivateKeyPemDescription()}
    visible: true

  autonomous_database_password:
    type: string
    title: ${Messages.solutionsHub.solutions.ordsModernAppDev.outputs.autonomousDatabasePasswordTitle()}
    displayText: ${Messages.solutionsHub.solutions.ordsModernAppDev.outputs.autonomousDatabasePasswordDescription()}
    visible: true